name = "ICAforECGrecordings"
uuid = "517f07d5-c0db-4eb4-a568-8213b39c7b3a"
authors = ["Tim Mueller-Bagehl <tim.mueller-bagehl@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DelimitedFiles = "1.9.1"
Plots = "1.40.13"
Statistics = "1.11.1"
julia = "1.11"