name = "ICAforECGrecordings"
uuid = "517f07d5-c0db-4eb4-a568-8213b39c7b3a"
authors = ["Tim Mueller-Bagehl <tim.mueller-bagehl@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
CSV = "0.10.15"
DelimitedFiles = "1.9.1"
Plots = "1.40.13"
julia = "1.11"
