name = "ICAforECGrecordings"
uuid = "517f07d5-c0db-4eb4-a568-8213b39c7b3a"
authors = ["Tim Mueller-Bagehl <tim.mueller-bagehl@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
DelimitedFiles = "1.9.1"
Plots = "1.40.13"
Revise = "3.8.0"
julia = "1.11"
